### ISSUE TITLE
Common Message Object

### ISSUE THREAD

**Issue by amod0017** [amod0017/otheloGameProject#2]
There should be someway to communicate over here. I think a common message object can be created with message type and message (as string) in it. This will sort lot of things on server side and will make code more readable. However this is not important as of now. Can be done once we are done with communicating. Let me know your views on it.

Thanks
Amod

**Comment by ghost** [comment]
I'm not sure that fundamentally changing the class diagram two days before the project is due is a good idea.  I'm looking at the progress of the message interface and it seems to be just a wrapper for a string.  You mentioned that this allows for both classes to send an object of a common class, but there's no reason that this couldn't be accomplished with String.

http://zedshaw.com/archive/indirection-is-not-abstraction/

**Comment by amod0017** [comment]
The fundamental purpose of making a typical message object to stay away from a greater amount of String parsing and making code more sorted out. Message class getMessageType() specifically offers you some assistance with understanding what sort of request it is. On the off chance that it is a game related request you simply need to check for three alternatives: 1. Begin the game 2. Stop the game and 3. Make a move. At this moment you are comparing it with everything. I don't think sending an object of a class which is now made is such a tremendous effort (You just have to do new Message("make a move 3,5", "game") while sending message). If you want to you can stay away from this for just a game demo yet at some point or another you will require this. However choice is yours since you are the team pioneer.
